export const mockCategories = [
  {
    id: 1,
    name: "Máy ảnh",
    description: "Professional DSLR cameras for photography",
    imageUrl: "/images/categories/dslr.jpg",
    productCount: 15,
    slug: "may-anh",
    subcategories: [
      { id: 11, name: "Máy ảnh Canon", slug: "may-anh-canon" },
      { id: 12, name: "Máy ảnh Fujifilm", slug: "may-anh-fujifilm" },
      { id: 13, name: "Máy ảnh Sony", slug: "may-anh-sony" },
      { id: 14, name: "Máy ảnh Nikon", slug: "may-anh-nikon" },
      { id: 15, name: "Máy ảnh Compact", slug: "may-anh-compact" },
    ],
  },
  {
    id: 2,
    name: "Ống kính",
    description: "Modern mirrorless camera systems",
    imageUrl: "/images/categories/mirrorless.jpg",
    productCount: 12,
    slug: "ong-kinh",
    subcategories: [
      { id: 21, name: "Ống kính wide", slug: "ong-kinh-wide" },
      { id: 22, name: "Ống kính zoom", slug: "ong-kinh-zoom" },
      { id: 23, name: "Ống kính macro", slug: "ong-kinh-macro" },
    ],
  },
  {
    id: 3,
    name: "Gimbal",
    description: "Compact and easy to use cameras",
    imageUrl: "/images/categories/compact.jpg",
    productCount: 8,
    slug: "gimbal",
    subcategories: [],
  },
  {
    id: 4,
    name: "Camera hành động",
    description: "Wide variety of camera lenses",
    imageUrl: "/images/categories/lenses.jpg",
    productCount: 25,
    slug: "camera-hanh-dong",
    subcategories: [
      { id: 41, name: "GoPro", slug: "gopro" },
      { id: 42, name: "DJI Osmo", slug: "dji-osmo" },
    ],
  },
  {
    id: 5,
    name: "Micro",
    description: "Camera accessories and gear",
    imageUrl: "/images/categories/accessories.jpg",
    productCount: 40,
    slug: "micro",
    subcategories: [
      { id: 51, name: "Micro thu âm", slug: "micro-thu-am" },
      { id: 52, name: "Micro không dây", slug: "micro-khong-day" },
    ],
  },
  {
    id: 8,
    name: "Phụ kiện",
    slug: "phu-kien",
    subcategories: [
      { id: 81, name: "Pin, Sạc", slug: "pin-sac" },
      { id: 82, name: "Túi, Balo", slug: "tui-balo" },
      { id: 83, name: "Tripod", slug: "tripod" },
    ],
  },
];
